### ISSUE TITLE
Problem with Talpa

### ISSUE THREAD

**Issue by erfan1185** [pyrocko/kite#101]
I am continuously encountering problem with Talpa, Spool works fine. Whenever I call Talpa, following error occurs;

Traceback (most recent call last):
  File "/home/irfan11/anaconda3/bin/talpa", line 5, in <module>
    from kite.talpa.__main__ import main
  File "/home/irfan11/anaconda3/lib/python3.9/site-packages/kite/talpa/__init__.py", line 1, in <module>
    from .talpa import Talpa  # noqa
  File "/home/irfan11/anaconda3/lib/python3.9/site-packages/kite/talpa/talpa.py", line 11, in <module>
    from .sources_dock import SourcesListDock
  File "/home/irfan11/anaconda3/lib/python3.9/site-packages/kite/talpa/sources_dock.py", line 98, in <module>
    class SourcesList(QtGui.QListView):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QListView'

![Talpa_Error](https://user-images.githubusercontent.com/127940561/225538422-68e21255-a291-421c-a3b4-ae3fcdbcde7d.png)

**Comment by erfan1185** [comment]
Thanks for the help. I will update kite and will recheck the problem.
