### ISSUE TITLE
ImportError: Could not recognize format for ascending

### ISSUE THREAD

**Issue by Suansuan0922** [pyrocko/kite#112]
Based on the example given, run spool --load ascending, but an error occurs
`Traceback (most recent call last):
  File "/home/u/anaconda3/bin/spool", line 8, in <module>
    sys.exit(main())
  File "/home/u/anaconda3/lib/python3.10/site-packages/kite/spool/__main__.py", line 111, in main
    spool(import_file=ns.load)
  File "/home/u/anaconda3/lib/python3.10/site-packages/kite/spool/spool.py", line 393, in spool
    spool_app = Spool(*args, **kwargs)
  File "/home/u/anaconda3/lib/python3.10/site-packages/kite/spool/spool.py", line 46, in __init__
    self.importScene(import_file)
  File "/home/u/anaconda3/lib/python3.10/site-packages/kite/spool/spool.py", line 61, in importScene
    self.spool_win.model.importFile(filename)
  File "/home/u/anaconda3/lib/python3.10/site-packages/kite/spool/scene_model.py", line 171, in importFile
    self.setScene(Scene.import_data(filename))
  File "/home/u/anaconda3/lib/python3.10/site-packages/kite/scene.py", line 459, in dynclassmethod
    return func(Scene(), *args, **kwargs)
  File "/home/u/anaconda3/lib/python3.10/site-packages/kite/scene.py", line 972, in _import_data
    raise ImportError("Could not recognize format for %s" % path)
ImportError: Could not recognize format for ascending
`

**Comment by hvasbath** [comment]
That means your data does not conform to the datatype format required. What data do you try to import?

**Comment by Suansuan0922** [comment]
> That means your data does not conform to the datatype format required. What data do you try to import?

I run `ariaExtract.py -w ascending -f S1-GUNW-A-R-064-tops-20190710_20180703-015013-36885N_35006N-PP-9955-v2_0_2.nc -d download -l unwrappedPhase,incidenceAngle,azimuthAngle` and get the ascending folder.  

![1700047499(1)](https://github.com/pyrocko/kite/assets/147323171/50ae8796-2948-4994-ab8b-5481a917deb1)

These are files of type.hrd,.vrt,.xml, .json, .dem

**Comment by hvasbath** [comment]
For the ARIA scene_io class you need to have osgeo ie. gdal installed. Please do so and try again!

**Comment by Suansuan0922** [comment]
I have already installed gdal, but still have this problem.

Requirement already satisfied: gdal in ./anaconda3/lib/python3.10/site-packages (3.6.2)

**Comment by hvasbath** [comment]
Thank you for your report! I will try to get rid of the gdal dependency in a patch and will keep you posted!
