### ISSUE TITLE
TypeError: setValue when running scene.spool()  

### ISSUE THREAD

**Issue by Thomas-Ulrich** [pyrocko/kite#114]
Hi,

I'm running the following script:
```python
(base) ulrich@ulrich-ThinkPad-T490s:~/work/Aqaba/Aqaba_INSar$ cat test.py 
from kite import Scene
import kite
print(kite.__version__)
# Import Matlab container to kite
scene = Scene.load('data/A_T343co')
scene.spool()  # start the GUI for data inspection and Quadtree parametrisation
```
With a file that Hannes Vasyurabathke provided me 2 years ago.
The file should be fine, as I can process the data and plot them with matplotlib.
But when I try running the gui, I get the following error:

```bash
(base) ulrich@ulrich-ThinkPad-T490s:~/work/Aqaba/Aqaba_INSar$ python test.py 
1.5.7
Traceback (most recent call last):
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 158, in buildViews
    self.addView(v)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 175, in addView
    view = view(self)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/tab_scene.py", line 56, in __init__
    self.dialogTransect = KiteToolTransect(scene_plot, spool)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/tab_scene.py", line 196, in __init__
    self.plt_wdgt.showGrid(True, True, alpha=0.5)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 376, in showGrid
    self.ctrl.gridAlphaSlider.setValue(v)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'numpy.float64'
Traceback (most recent call last):
  File "/home/ulrich/work/Aqaba/Aqaba_INSar/test.py", line 6, in <module>
    scene.spool()  # start the GUI for data inspection and Quadtree parametrisation
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/scene.py", line 854, in spool
    spool(scene=self)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 393, in spool
    spool_app = Spool(*args, **kwargs)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 44, in __init__
    self.addScene(scene)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 58, in addScene
    self.spool_win.addScene(scene)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 147, in addScene
    self.buildViews()
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 158, in buildViews
    self.addView(v)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 175, in addView
    view = view(self)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/tab_scene.py", line 56, in __init__
    self.dialogTransect = KiteToolTransect(scene_plot, spool)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/tab_scene.py", line 196, in __init__
    self.plt_wdgt.showGrid(True, True, alpha=0.5)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 376, in showGrid
    self.ctrl.gridAlphaSlider.setValue(v)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'numpy.float64'
```
(Python 3.10.13)

**Comment by Thomas-Ulrich** [comment]
Hi!
It does not work this way for me (I also tried the yml and npz files):
```bash
(base) ulrich@ulrich-ThinkPad-T490s:~/work/Aqaba/Aqaba_INSar/data$ spool --load=A_T343co
Traceback (most recent call last):
  File "/home/ulrich/mambaforge3/bin/spool", line 8, in <module>
    sys.exit(main())
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/__main__.py", line 111, in main
    spool(import_file=ns.load)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 393, in spool
    spool_app = Spool(*args, **kwargs)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 46, in __init__
    self.importScene(import_file)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/spool.py", line 61, in importScene
    self.spool_win.model.importFile(filename)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/spool/scene_model.py", line 171, in importFile
    self.setScene(Scene.import_data(filename))
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/scene.py", line 459, in dynclassmethod
    return func(Scene(), *args, **kwargs)
  File "/home/ulrich/mambaforge3/lib/python3.10/site-packages/kite/scene.py", line 960, in _import_data
    raise ImportError("File %s does not exist!" % path)
ImportError: File A_T343co does not exist!
(base) ulrich@ulrich-ThinkPad-T490s:~/work/Aqaba/Aqaba_INSar/data$ ls 
A_T114do.npz  A_T114do.yml  A_T114up.npz  A_T114up.yml  A_T343co.npz  A_T343co.yml  D_T254co.npz  D_T254co.yml  D_T350co.npz  D_T350co.yml  fault_model_ribot_et_al_transformed.txt
```

**Comment by hvasbath** [comment]
Ah sorry my bas- its already imported to kite format. Then just:
```
spool A_T343co.yml
```

should do the trick

**Comment by hvasbath** [comment]
Hi Thomas again!

I now understood the root of your initial issue. There is a problem in pyqtgraph version 0.11-0.12, starting with pyqtgraph 0.13 your import should work-at least it works for me on python3.11 ubuntu 20,04. See here: https://github.com/pyqtgraph/pyqtgraph/pull/1809

Sorry for the inconvenience!

**Comment by Thomas-Ulrich** [comment]
I confirm it works!

**Comment by emolch** [comment]
Thanks, please let me know when there are some remaining issues in the GUI. I only did some shallow testing and there may be more things which have to be adjusted to support that range of pyqtgraph versions.

**Comment by Thomas-Ulrich** [comment]
as far as I tested, everything works fine.

**Comment by mmustacb** [comment]
Hi,

I have a similar problem after installing kite with pip in a conda base environment (I did not manage to install it without using pip). However, the above command did not work for me, I get the following output:

> (base) marija@marija-MS-7C37:/media/marija/New Volume1/InSAR/Kite/test_COMET_LiSCAR$ pip install git+https://github.com/pyrocko/kite.git@bugfix/compatibility
> Collecting git+https://github.com/pyrocko/kite.git@bugfix/compatibility
>   Cloning https://github.com/pyrocko/kite.git (to revision bugfix/compatibility) to /tmp/pip-req-build-gs0wsgmr
>   Running command git clone --filter=blob:none --quiet https://github.com/pyrocko/kite.git /tmp/pip-req-build-gs0wsgmr
>   WARNING: Did not find branch or tag 'bugfix/compatibility', assuming revision or ref.
>   Running command git checkout -q bugfix/compatibility
>   error: pathspec 'bugfix/compatibility' did not match any file(s) known to git
>   error: subprocess-exited-with-error
>   
>   × git checkout -q bugfix/compatibility did not run successfully.
>   │ exit code: 1
>   ╰─> See above for output.
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × git checkout -q bugfix/compatibility did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

Has something changed with bugfix/compatibility in the meantime or is the problem on my side? 

(Python 3.11.5)

**Comment by hvasbath** [comment]
Hi! The bugfix/compatibility branch has been merged into master and was deleted. Please checkout the master branch! A new pip package has not been released yet-as we want to fix sth else as well for the new release.
