### ISSUE TITLE
wrong_argument types for .tif data

### ISSUE THREAD

**Issue by mnergizci** [pyrocko/kite#123]
Hi I would like to use spool -load dataset.tif but I get error as below, could you please help me to solve it?

[mnergiz@sci8.jasmin.ac.uk downsample_kite]$ spool --load 021D_azi_ref2dummyfull.tif
Traceback (most recent call last):
  File "/home/users/mnergiz/.conda/envs/mnergizci/bin/spool", line 5, in <module>
    from kite.spool.__main__ import main
  File "/home/users/mnergiz/.conda/envs/mnergizci/lib/python3.11/site-packages/kite/spool/__init__.py", line 2, in <module>
    from .spool import Spool, spool
  File "/home/users/mnergiz/.conda/envs/mnergizci/lib/python3.11/site-packages/kite/spool/spool.py", line 17, in <module>
    from .tab_aps import KiteAPS  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/mnergiz/.conda/envs/mnergizci/lib/python3.11/site-packages/kite/spool/tab_aps.py", line 10, in <module>
    from .tab_covariance import KiteSubplot
  File "/home/users/mnergiz/.conda/envs/mnergizci/lib/python3.11/site-packages/kite/spool/tab_covariance.py", line 14, in <module>
    pen_covariance_model = pg.mkPen((204, 0, 0), width=2, style=QtCore.Qt.DotLine)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/mnergiz/.conda/envs/mnergizci/lib/python3.11/site-packages/pyqtgraph/functions.py", line 366, in mkPen
    pen.setStyle(style)
TypeError: 'PySide6.QtGui.QPen.setStyle' called with wrong argument types:
  PySide6.QtGui.QPen.setStyle(PenStyle)
Supported signatures:
  PySide6.QtGui.QPen.setStyle(PySide6.QtCore.Qt.PenStyle)

**Comment by miili** [comment]
Yes, please downgrade to PyQt5.
