### ISSUE TITLE
Error in Spool for LiCSAR images

### ISSUE THREAD

**Issue by erlangga0909** [pyrocko/kite#127]
I am new in Pyrocko - Kite, i have been in trouble to install it.

right now, i got an error in spool command like this

spool --load=./20180214_20180220.geo.unw.tif
Traceback (most recent call last):
  File "/home/asep/Desktop/pyrocko2/pyroenv/bin/spool", line 5, in <module>
    from spool.main import cli
  File "/home/asep/Desktop/pyrocko2/pyroenv/lib/python3.12/site-packages/spool/main.py", line 11, in <module>
    from .message import Message, MessageError
  File "/home/asep/Desktop/pyrocko2/pyroenv/lib/python3.12/site-packages/spool/message.py", line 16, in <module>
    from .smime import encrypt, sign
  File "/home/asep/Desktop/pyrocko2/pyroenv/lib/python3.12/site-packages/spool/smime.py", line 6, in <module>
    from ctypescrypto.cipher import CipherType
  File "/home/asep/Desktop/pyrocko2/pyroenv/lib/python3.12/site-packages/ctypescrypto/cipher.py", line 245, in <module>
    libcrypto.EVP_CIPHER_block_size.argtypes = (c_void_p, )
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 392, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ctypes/__init__.py", line 397, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /lib/x86_64-linux-gnu/libcrypto.so.3: undefined symbol: EVP_CIPHER_block_size

while, my pip env list like this :
affine==2.4.0
attrs==24.2.0
Cerberus==1.3.5
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
contourpy==1.3.0
cryptography==43.0.3
ctypescrypto==0.5
cycler==0.12.1
dkimpy==1.1.8
dnspython==2.7.0
fonttools==4.54.1
GDAL==3.9.3
geojson==3.1.0
idna==3.10
Jinja2==3.1.4
kite==1.5.8
kiwisolver==1.4.7
MarkupSafe==3.0.2
matplotlib==3.9.2
numpy==1.26.4
packaging==24.1
pillow==11.0.0
pycparser==2.22
pyparsing==3.2.0
PyQt5==5.15.11
PyQt5-Qt5==5.15.15
PyQt5_sip==12.15.0
pyqtgraph==0.13.7
PyQtWebEngine==5.15.7
PyQtWebEngine-Qt5==5.15.15
pyrocko @ file:///home/asep/Desktop/pyrocko2/pyrocko
python-dateutil==2.9.0.post0
PyYAML==6.0.2
rasterio==1.4.2
requests==2.32.3
scipy==1.14.1
setuptools==75.3.0
six==1.16.0
spool==0.9.9
urllib3==2.2.3
utm==0.7.0

**Comment by miili** [comment]
Looking at the traceback the problem is a with `libcrypto` and not kite.
