### ISSUE TITLE
test files

### ISSUE THREAD

**Issue by mohseniaref** [pyrocko/kite#19]
Hi,

I faced error when I run test files.The common.py is in the same folder.woudl you please guide me how to solve this problem

best,
Mohammad

```
earth@naranj:~/Software/pyrocko/kite/test$ python test_source_okada.py
Traceback (most recent call last):
  File "test_source_okada.py", line 9, in <module>
    from . import common
ValueError: Attempted relative import in non-package
```

**Comment by miili** [comment]
We use `nosetests` for testing:

try:
```
sudo pip install nose
cd kite-folder
nosetests test
```

**Comment by mohseniaref** [comment]
Hi

after nosetests test ,you can see the error messages


arth@naranj:~/Software/pyrocko/kite$ nosetests test
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
test_covariance (test.test_covariance.TestCovariance) ... ERROR
test_synthetic_noise (test.test_covariance.TestCovariance) ... ERROR
test_import_gamma (test.test_io.SceneIOTest) ... ok
test_import_gmtsar (test.test_io.SceneIOTest) ... ok
test_import_isce (test.test_io.SceneIOTest) ... ok
test_import_matlab (test.test_io.SceneIOTest) ... Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
ok
test_import_roi_pac (test.test_io.SceneIOTest) ... ok
testQuadtree (test.test_scene.TestSyntheticScene) ... ERROR
testFractal (test.test_scene.TestSyntheticsGenerators) ... ok
testGauss (test.test_scene.TestSyntheticsGenerators) ... ok
testSine (test.test_scene.TestSyntheticsGenerators) ... ok
testEllipsoidSource (test.test_source_compound_models.CompoundModelsTest) ... ok
testPointCompoundSourceSource (test.test_source_compound_models.CompoundModelsTest) ... ok
test_ECM (test.test_source_compound_models.CompoundModelsTest) ... /usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/sources/compound_engine.py:43: RuntimeWarning: invalid value encountered in divide
  Vstrike = Vstrike / num.linalg.norm(Vstrike)
ok
testModelSaveLoad (test.test_source_okada.testSourceOkada) ... ok
test_okada_source (test.test_source_okada.testSourceOkada) ... ok
test_double_couple (test.test_source_pyrocko.testSourcePyrocko) ... ok
test_moment_tensor (test.test_source_pyrocko.testSourcePyrocko) ... ok
test_rectangular_source (test.test_source_pyrocko.testSourcePyrocko) ... ok
test_ring_fault (test.test_source_pyrocko.testSourcePyrocko) ... ok

======================================================================
ERROR: test_covariance (test.test_covariance.TestCovariance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earth/Software/pyrocko/kite/test/test_covariance.py", line 21, in test_covariance
    cov = self.sc.covariance
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 582, in covariance
    return Covariance(scene=self, config=self.config.covariance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/covariance.py", line 121, in __init__
    self.quadtree = scene.quadtree
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 572, in quadtree
    return Quadtree(scene=self, config=self.config.quadtree)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 371, in __init__
    self.setConfig(config)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 385, in setConfig
    self.setCorrection(self.config.correction)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 422, in setCorrection
    self._initTree()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 434, in _initTree
    b.createTree()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 261, in createTree
    if (self.quadtree._corr_func(self) > self.quadtree.epsilon_min
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 346, in <lambda>
    ['Std around median', lambda n: n.corr_median],
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 79, in corr_median
    return num.nanstd(self.displacement - self.median)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 58, in median
    return num.nanmedian(self.displacement)
AttributeError: 'module' object has no attribute 'nanmedian'
-------------------- >> begin captured logging << --------------------
kite.testing: INFO: Downloading http://data.pyrocko.org/testing/kite/myanmar_alos_dsc_ionocorr.mat...
urllib3.connectionpool: INFO: Starting new HTTP connection (1): data.pyrocko.org
urllib3.connectionpool: DEBUG: Setting read timeout to None
urllib3.connectionpool: DEBUG: "HEAD /testing/kite/myanmar_alos_dsc_ionocorr.mat HTTP/1.1" 200 0
urllib3.connectionpool: INFO: Starting new HTTP connection (1): data.pyrocko.org
urllib3.connectionpool: DEBUG: Setting read timeout to <object object at 0x7f514f12b0c0>
urllib3.connectionpool: DEBUG: "GET /testing/kite/myanmar_alos_dsc_ionocorr.mat HTTP/1.1" 200 8575883
kite.testing: INFO: Download completed.
Scene: DEBUG: Importing /home/earth/Software/pyrocko/kite/test/data/myanmar_alos_dsc_ionocorr.mat using Matlab module
Scene.IO/Matlab: WARNING: Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Scene: DEBUG: Creating kite.Covariance instance
Scene: DEBUG: Creating kite.Quadtree instance
Scene.Quadtree: DEBUG: Changing to split method 'median'
Scene.Quadtree: DEBUG: Creating 2 base nodes
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_synthetic_noise (test.test_covariance.TestCovariance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earth/Software/pyrocko/kite/test/test_covariance.py", line 36, in test_synthetic_noise
    self.sc.covariance.syntheticNoise()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 582, in covariance
    return Covariance(scene=self, config=self.config.covariance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/covariance.py", line 121, in __init__
    self.quadtree = scene.quadtree
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 572, in quadtree
    return Quadtree(scene=self, config=self.config.quadtree)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 371, in __init__
    self.setConfig(config)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 385, in setConfig
    self.setCorrection(self.config.correction)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 422, in setCorrection
    self._initTree()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 434, in _initTree
    b.createTree()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 261, in createTree
    if (self.quadtree._corr_func(self) > self.quadtree.epsilon_min
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 346, in <lambda>
    ['Std around median', lambda n: n.corr_median],
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 79, in corr_median
    return num.nanstd(self.displacement - self.median)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 58, in median
    return num.nanmedian(self.displacement)
AttributeError: 'module' object has no attribute 'nanmedian'
-------------------- >> begin captured logging << --------------------
Scene: DEBUG: Creating kite.Covariance instance
Scene: DEBUG: Creating kite.Quadtree instance
Scene.Quadtree: DEBUG: Changing to split method 'median'
Scene.Quadtree: DEBUG: Creating 2 base nodes
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: testQuadtree (test.test_scene.TestSyntheticScene)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/earth/Software/pyrocko/kite/test/test_scene.py", line 26, in setUp
    self.sc.quadtree.epsilon = .02
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 572, in quadtree
    return Quadtree(scene=self, config=self.config.quadtree)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 371, in __init__
    self.setConfig(config)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 385, in setConfig
    self.setCorrection(self.config.correction)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 422, in setCorrection
    self._initTree()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 434, in _initTree
    b.createTree()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 261, in createTree
    if (self.quadtree._corr_func(self) > self.quadtree.epsilon_min
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 346, in <lambda>
    ['Std around median', lambda n: n.corr_median],
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 79, in corr_median
    return num.nanstd(self.displacement - self.median)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/util.py", line 134, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/quadtree.py", line 58, in median
    return num.nanmedian(self.displacement)
AttributeError: 'module' object has no attribute 'nanmedian'
-------------------- >> begin captured logging << --------------------
TestScene: DEBUG: Creating kite.Quadtree instance
TestScene.Quadtree: DEBUG: Changing to split method 'median'
TestScene.Quadtree: DEBUG: Creating 1 base nodes
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 20 tests in 164.567s

FAILED (errors=3)

**Comment by miili** [comment]
Hi Mohammad,

can you check your numpy version? `numpy.nanmedian` was introduced in version 1.9.0

`sudo pip --upgrade install numpy`

**Comment by mohseniaref** [comment]
Hi,

I think you mean sudo easy_install --upgrade install numpy,It seems the problem was related to numpy.The test passed successfully.

Best,
Mohammad

earth@naranj:~/Software/pyrocko/kite$ nosetests test
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
test_covariance (test.test_covariance.TestCovariance) ... ok
test_synthetic_noise (test.test_covariance.TestCovariance) ... ok
test_import_gamma (test.test_io.SceneIOTest) ... ok
test_import_gmtsar (test.test_io.SceneIOTest) ... ok
test_import_isce (test.test_io.SceneIOTest) ... ok
test_import_matlab (test.test_io.SceneIOTest) ... Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
Variable utm_zone not defined. Defaulting to UTM Zone 33N!
ok
test_import_roi_pac (test.test_io.SceneIOTest) ... ok
testQuadtree (test.test_scene.TestSyntheticScene) ... ok
testFractal (test.test_scene.TestSyntheticsGenerators) ... ok
testGauss (test.test_scene.TestSyntheticsGenerators) ... ok
testSine (test.test_scene.TestSyntheticsGenerators) ... ok
testEllipsoidSource (test.test_source_compound_models.CompoundModelsTest) ... ok
testPointCompoundSourceSource (test.test_source_compound_models.CompoundModelsTest) ... ok
test_ECM (test.test_source_compound_models.CompoundModelsTest) ... /usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/sources/compound_engine.py:43: RuntimeWarning: invalid value encountered in divide
  Vstrike = Vstrike / num.linalg.norm(Vstrike)
ok
testModelSaveLoad (test.test_source_okada.testSourceOkada) ... ok
test_okada_source (test.test_source_okada.testSourceOkada) ... ok
test_double_couple (test.test_source_pyrocko.testSourcePyrocko) ... ok
test_moment_tensor (test.test_source_pyrocko.testSourcePyrocko) ... ok
test_rectangular_source (test.test_source_pyrocko.testSourcePyrocko) ... ok
test_ring_fault (test.test_source_pyrocko.testSourcePyrocko) ... ok

----------------------------------------------------------------------
Ran 20 tests in 76.520s

OK

**Comment by mohseniaref** [comment]
Hi,

I am working with test data based on tutorial instruction.It seems the spool is not working properly.

Best,
Mohammad 

earth@naranj:~/Software/pyrocko/kite/test/data$ spool 20110214_20110401_ml4_sm.unw.geo_ig_dsc_ionnocorr.mat
Traceback (most recent call last):
  File "/usr/local/bin/spool", line 9, in <module>
    load_entry_point('kite==0.0.2.post20171009', 'console_scripts', 'spool')()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/spool/__main__.py", line 76, in main
    Spool(load_file=ns.file)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/spool/spool.py", line 43, in __init__
    self.loadScene(load_file)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/spool/spool.py", line 62, in loadScene
    self.spool_win.model.loadFile(filename)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/spool/scene_model.py", line 134, in loadFile
    self.setScene(Scene.load(filename))
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 347, in dynclassmethod
    return func(Scene(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 671, in _load
    raise UserIOWarning('Could not load data from %s.npz' % basename)
kite.scene.UserIOWarning: Could not load data from 20110214_20110401_ml4_sm.unw.geo_ig_dsc_ionnocorr.npz
QThread: Destroyed while thread is still running
earth@naranj:~/Software/pyrocko/kite/test/data$ spool 20110214_20110401_ml4_sm.unw.geo_ig_dsc_ionnocorr.mat
Traceback (most recent call last):
  File "/usr/local/bin/spool", line 9, in <module>
    load_entry_point('kite==0.0.2.post20171009', 'console_scripts', 'spool')()
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/spool/__main__.py", line 76, in main
    Spool(load_file=ns.file)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/spool/spool.py", line 43, in __init__
    self.loadScene(load_file)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/spool/spool.py", line 62, in loadScene
    self.spool_win.model.loadFile(filename)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/spool/scene_model.py", line 134, in loadFile
    self.setScene(Scene.load(filename))
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 347, in dynclassmethod
    return func(Scene(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kite-0.0.2.post20171009-py2.7-linux-x86_64.egg/kite/scene.py", line 671, in _load
    raise UserIOWarning('Could not load data from %s.npz' % basename)
kite.scene.UserIOWarning: Could not load data from 20110214_20110401_ml4_sm.unw.geo_ig_dsc_ionnocorr.npz
QThread: Destroyed while thread is still running
earth@naranj:~/Software/pyrocko/kite/test/data$

**Comment by miili** [comment]
Hi Mohammad,

excellent the chekcs pass now! `pip` is another package manager, complementary to `easy_install`.

The `.mat` file has to be imported, use `spool --load 20110214_20110401_ml4_sm.unw.geo_ig_dsc_ionnocorr.mat` to open the file.

Once it is open you can save the `.mat` file in kite's native format which consits of a numpy container and a YAML file.

best regards,

M

**Comment by mohseniaref** [comment]
Hi Marius,

yes,of course!I mean you wanted to write sudo easy_install --upgrade install numpy or sudo pip install numpy --upgrade ,you wrote sudo pip --upgrade install numpy and It is not working!

Thanks for your explanation.Spool works well.this tutorial page should be corrected https://pyrocko.github.io/kite/spool.html ,

I wonder if you included okada inversion and slip distribution estimation using another source model?

Best,
MM

**Comment by miili** [comment]
Hey Mohammad,

kite will only do some pre-inversion processing of the displacement. The tool talpa is designed for educational use and could be used for constraining a start model.

You can find a list of implemented displacement sources here: 

https://pyrocko.github.io/kite/examples/05-sandbox.html

and https://pyrocko.github.io/kite/talpa.html

best,

Marius
