### ISSUE TITLE
Talpa programmatic start

### ISSUE THREAD

**Issue by hvasbath** [pyrocko/kite#45]
Following script adapted from your example 

```python
from kite import SandboxScene
from kite.sources import EllipsoidSource
from kite.talpa import Talpa

fn = '/tmp/sandbox_scene.yml'
km = 1e3

sandbox = SandboxScene()

ellipsoid_source = EllipsoidSource(
    northing=40*km,
    easting=40*km,
    depth=4*km,
    length_x=100,
    length_y=200,
    length_z=350,
    rotation_x=42.)
sandbox.addSource(ellipsoid_source)

sandbox.save(fn)

Talpa(filename=fn)
```

raises following error on python 3.6 using Ubuntu 18.04.

```
INFO:TalpaConfig:Loading config from /home/vasyurhm/.config/kite/talpa_config.yml...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kite-2018.2.26-py3.6-linux-x86_64.egg/kite/util.py", line 220, in unsubscribe
    self._listeners.remove(listener)
ValueError: list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "talpa_test.py", line 22, in <module>
    Talpa(filename=fn)
  File "/usr/local/lib/python3.6/dist-packages/kite-2018.2.26-py3.6-linux-x86_64.egg/kite/talpa/talpa.py", line 30, in __init__
    self.talpa_win = TalpaMainWindow(filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/kite-2018.2.26-py3.6-linux-x86_64.egg/kite/talpa/talpa.py", line 85, in __init__
    self.loadModel(filename)
  File "/usr/local/lib/python3.6/dist-packages/kite-2018.2.26-py3.6-linux-x86_64.egg/kite/talpa/talpa.py", line 130, in loadModel
    self.sandbox.setModel(model)
  File "/usr/local/lib/python3.6/dist-packages/kite-2018.2.26-py3.6-linux-x86_64.egg/kite/talpa/sandbox_model.py", line 49, in setModel
    self.disconnectSlots()
  File "/usr/local/lib/python3.6/dist-packages/kite-2018.2.26-py3.6-linux-x86_64.egg/kite/talpa/sandbox_model.py", line 66, in disconnectSlots
    self.model.evModelUpdated.unsubscribe(self.sigModelUpdated.emit)
  File "/usr/local/lib/python3.6/dist-packages/kite-2018.2.26-py3.6-linux-x86_64.egg/kite/util.py", line 222, in unsubscribe
    raise AttributeError('%s was not subscribed!')
AttributeError: %s was not subscribed!
```

**Comment by hvasbath** [comment]
Version issue, fixed in new versions ...
