### ISSUE TITLE
LiCSAR import broken

### ISSUE THREAD

**Issue by braunfuss** [pyrocko/kite#50]
Using the example from docs to download LiCSAR data fails:

```
python3 -m kite.clients http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/6/006D_05509_131313/products/20171107_20171201/20171107_20171201.geo.unw.tif .

spool --load=./20171107_20171201.geo.unw.tif
QApplication: invalid style override passed, ignoring it.
Traceback (most recent call last):
  File "/usr/local/bin/spool", line 11, in <module>
    load_entry_point('kite==1.3.0', 'console_scripts', 'spool')()
  File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/__main__.py", line 87, in main
    spool(import_file=ns.load)
  File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/spool.py", line 304, in spool
    spool_app = Spool(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/spool.py", line 42, in __init__
    self.importScene(import_file)
  File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/spool.py", line 58, in importScene
    self.spool_win.model.importFile(filename)
  File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/scene_model.py", line 134, in importFile
    self.setScene(Scene.import_data(filename))
  File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/scene.py", line 431, in dynclassmethod
    return func(Scene(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/scene.py", line 907, in _import_data
    raise ImportError('Could not recognize format for %s' % path)
ImportError: Could not recognize format for ./20171107_20171201.geo.unw.tif
```

**Comment by miili** [comment]
Strange, cannot reproduce. Does work here.

**Comment by hvasbath** [comment]
works also here ... however:

**Comment by braunfuss** [comment]
Yes - on dev branch and sparrow branches of pyrocko i also have the same error as @hvasbath.
Also kite master should work on the pyrocko master branch and not depend on dev branches for easy access for people...

**Comment by braunfuss** [comment]
To clarify: my original error occurs on master kite and master pyrocko. I am happy if its just my problem of course ;-)

**Comment by hsudha** [comment]
I checked with both pyrocko and kite masters and it worked.

**Comment by hvasbath** [comment]
How is that possible @hsudha ? Here: there is no dataset.util module in the master:
https://github.com/pyrocko/pyrocko/tree/master/src/dataset

You have to be on a different branch ...

**Comment by braunfuss** [comment]
The ImportError: Could not recognize format seems to be a local issue on this particular machines environment but turns up for non-native imports like aria, licsar, gmtsar. 
Any idea what the culprit could be? Else we can close this issue and maybe open a new one for the ModuleNotFoundError: No module named 'pyrocko.dataset.util'

**Comment by miili** [comment]
The import uses `osgeo.gdal` which is a pain to install :(

Yet the system packages on Debian based distros work:
```
apt-get install python3-gdal
```

**Comment by braunfuss** [comment]
Indeed on the system in questions gdal python3 bindings were not installed and issue was solved accordingly. Maybe a dedicated error message would be helpful for other users.

**Comment by janesion** [comment]
> Using the example from docs to download LiCSAR data fails:
> 
> ```
> python3 -m kite.clients http://gws-access.ceda.ac.uk/public/nceo_geohazards/LiCSAR_products/6/006D_05509_131313/products/20171107_20171201/20171107_20171201.geo.unw.tif .
> 
> spool --load=./20171107_20171201.geo.unw.tif
> QApplication: invalid style override passed, ignoring it.
> Traceback (most recent call last):
>   File "/usr/local/bin/spool", line 11, in <module>
>     load_entry_point('kite==1.3.0', 'console_scripts', 'spool')()
>   File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/__main__.py", line 87, in main
>     spool(import_file=ns.load)
>   File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/spool.py", line 304, in spool
>     spool_app = Spool(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/spool.py", line 42, in __init__
>     self.importScene(import_file)
>   File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/spool.py", line 58, in importScene
>     self.spool_win.model.importFile(filename)
>   File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/spool/scene_model.py", line 134, in importFile
>     self.setScene(Scene.import_data(filename))
>   File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/scene.py", line 431, in dynclassmethod
>     return func(Scene(), *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/kite-1.3.0-py3.6-linux-x86_64.egg/kite/scene.py", line 907, in _import_data
>     raise ImportError('Could not recognize format for %s' % path)
> ImportError: Could not recognize format for ./20171107_20171201.geo.unw.tif
> ```

I'd like to know how you solved this problem, because I also encountered it. When loading the unw.tif, the unrecognized path is displayed. Very confused. Looking forward your reply! Thanks!

**Comment by hvasbath** [comment]
Reopening pinging @miili

**Comment by janesion** [comment]
I already know. Thank you !

**Comment by mmustacb** [comment]
Hi, I am getting the same error even though gdal is successfully installed (with the conda-forge channel) and working.

Python 3.11.7
gdal                      3.8.3           py311h39b4e0e_0    conda-forge
kite                      1.5.8.dev3+g1402f3c          pypi_0    pypi
pyrocko                   2024.01.10      py311h03063b4_0    pyrocko

**Comment by blancasl** [comment]
Hi, I have the same problem, I would like to know if someone could solve it? Thanks!.

**Comment by miili** [comment]
Can you please paste your error message?

**Comment by blancasl** [comment]
(kite) bsymmes@tecto-97:~/Desktop/KITE/Licsbas$ spool --load 20250324_20250405.geo.unw.tif 
Traceback (most recent call last):
  File "/home/bsymmes/anaconda3/envs/kite/bin/spool", line 8, in <module>
    sys.exit(main())
  File "/home/bsymmes/anaconda3/envs/kite/lib/python3.9/site-packages/kite/spool/main.py", line 111, in main
    spool(import_file=ns.load)
  File "/home/bsymmes/anaconda3/envs/kite/lib/python3.9/site-packages/kite/spool/spool.py", line 393, in spool
    spool_app = Spool(args, *kwargs)
  File "/home/bsymmes/anaconda3/envs/kite/lib/python3.9/site-packages/kite/spool/spool.py", line 46, in init
    self.importScene(import_file)
  File "/home/bsymmes/anaconda3/envs/kite/lib/python3.9/site-packages/kite/spool/spool.py", line 61, in importScene
    self.spool_win.model.importFile(filename)
  File "/home/bsymmes/anaconda3/envs/kite/lib/python3.9/site-packages/kite/spool/scene_model.py", line 171, in importFile
    self.setScene(Scene.import_data(filename))
  File "/home/bsymmes/anaconda3/envs/kite/lib/python3.9/site-packages/kite/scene.py", line 459, in dynclassmethod
    return func(Scene(), args, *kwargs)
  File "/home/bsymmes/anaconda3/envs/kite/lib/python3.9/site-packages/kite/scene.py", line 973, in _import_data
    raise ImportError("Could not recognize format for %s" % path)
ImportError: Could not recognize format for 20250324_20250405.geo.unw.tif

The data isn’t the problem — I tried the same files on another computer with Kite and they work fine. I also tried updating the GDAL package, but it didn’t help.

Anyone know how to fix this? Thanks!
