### ISSUE TITLE
APS correction and UTM Format scenes

### ISSUE THREAD

**Issue by braunfuss** [pyrocko/kite#57]
Seems to be an issue that scenes in UTM coordinates are not associated correctly to SRTMGL3 tiles.

INFO:Scene.APS:Applying APS model to displacement
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/spool/base.py", line 75, in run
    plot.model)
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/spool/tab_scene.py", line 93, in <lambda>
    ['Scene.displacement', lambda sp: sp.scene.displacement],
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/scene.py", line 815, in displacement
    plugin.apply(self._proc_displacement)
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/aps.py", line 78, in apply
    elevation = scene.get_elevation()
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/scene.py", line 697, in get_elevation
    'Region is outside of SRTMGL3 topo dataset')
AssertionError: Region is outside of SRTMGL3 topo dataset
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/spool/tab_aps.py", line 168, in update
    elevation, displacement = aps.get_data()
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/aps.py", line 59, in get_data
    elevation = self.get_elevation()[rowmin:rowmax, colmin:colmax]
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/aps.py", line 22, in get_elevation
    return self.scene.get_elevation()
  File "/usr/local/lib/python3.6/dist-packages/kite-1.4.0-py3.6-linux-x86_64.egg/kite/scene.py", line 697, in get_elevation
    'Region is outside of SRTMGL3 topo dataset')
AssertionError: Region is outside of SRTMGL3 topo dataset

**Comment by miili** [comment]
Hi Andi,

where is the scene located? SRTM unfortunately covers only to 60N to 58S.

M

**Comment by braunfuss** [comment]
Hey,
the issue is indeed that no SRTM tile is available. The location is however in the SRTM region. For some reason for that particular area however there is no tile available in the used dataset (could be a download issue). Maybe we could add a different assertion error for this kind of issue? Like AssertionError: SRTMGL3 topo tile is missing
