### ISSUE TITLE
PyQt5 issue

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [pyrocko/kite#70]
Dear all, 
I have a problem regarding PyQt as far as I understood,
I really appreciate it if you can help me to solve this issue? 
```
spool dsc
Traceback (most recent call last):
  File "/raid-manaslu/maref/Software/anaconda3/envs/mintpyc/bin/spool", line 5, in <module>
    from kite.spool.main import main
  File "/raid-manaslu/maref/Software/anaconda3/envs/mintpyc/lib/python3.8/site-packages/kite/spool/init.py", line 2, in <module>
    from .spool import Spool, spool
  File "/raid-manaslu/maref/Software/anaconda3/envs/mintpyc/lib/python3.8/site-packages/kite/spool/spool.py", line 10, in <module>
    from kite.qt_utils import loadUi, validateFilename, SceneLog, QRangeSlider
  File "/raid-manaslu/maref/Software/anaconda3/envs/mintpyc/lib/python3.8/site-packages/kite/qt_utils.py", line 98, in <module>
    class SliderWidget(QtGui.QWidget):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QWidget'
```

**Comment by miili** [comment]
Uh, this is weird. Which version of Qt is installed. Please try installing a recent version.
