### ISSUE TITLE
Failed in importing Scene function

### ISSUE THREAD

**Issue by bjmarfito** [pyrocko/kite#86]
When I try to import the scene function, an error occurs as shown below.

```
from kite import Scene
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bryanjim001/.conda/envs/pyrocko/lib/python3.9/site-packages/kite/__init__.py", line 4, in <module>
    from .scene import Scene, TestScene, read  # noqa
  File "/home/bryanjim001/.conda/envs/pyrocko/lib/python3.9/site-packages/kite/scene.py", line 12, in <module>
    from pyrocko.guts import Object, Float, StringChoice, String, Timestamp, Dict, load
  File "/home/data/INSAR_processing/urgent_response/S1_2022_Afghanistan_EQ/20220618_20220630_asc_topsStack/merged/interferograms/20220618_20220630/pyrocko.py", line 2, in <module>
    from kite import Scene
ImportError: cannot import name 'Scene' from partially initialized module 'kite' (most likely due to a circular import) (/home/bryanjim001/.conda/envs/pyrocko/lib/python3.9/site-packages/kite/__init__.py)
```

**Comment by bjmarfito** [comment]
I resolved it. The problem is the name of my code.
