### ISSUE TITLE
Exporting quadtree to csv failed 

### ISSUE THREAD

**Issue by raghav413** [pyrocko/kite#87]
Traceback (most recent call last):
  File "/home/raghav/gmt_sar/quadtree/test.py", line 33, in <module>
    qt.export_csv('tree.csv')
  File "/usr/local/lib/python3.10/dist-packages/kite-1.5.0-py3.10-linux-x86_64.egg/kite/quadtree.py", line 1004, in export_csv
    "{lf.id}, {lf.focal_point[0]}, {lf.focal_point[1]}, "
  File "/usr/local/lib/python3.10/dist-packages/kite-1.5.0-py3.10-linux-x86_64.egg/kite/util/__init__.py", line 138, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python3.10/dist-packages/kite-1.5.0-py3.10-linux-x86_64.egg/kite/quadtree.py", line 195, in theta
    theta = self.scene.theta[self._slice_rows, self._slice_cols]
TypeError: 'float' object is not subscriptable

AND when I used spool to export quadtree as csv  I get the following error

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/kite-1.5.0-py3.10-linux-x86_64.egg/kite/spool/spool.py", line 318, in onExportQuadtree
    self.model.quadtree.export_csv(filename)
  File "/usr/local/lib/python3.10/dist-packages/kite-1.5.0-py3.10-linux-x86_64.egg/kite/quadtree.py", line 1003, in export_csv
    "{lf.id}, {lf.focal_point[0]}, {lf.focal_point[1]}, "
  File "/usr/local/lib/python3.10/dist-packages/kite-1.5.0-py3.10-linux-x86_64.egg/kite/util/__init__.py", line 138, in cache_return
    instance.__dict__[var_name] = func(instance)
  File "/usr/local/lib/python3.10/dist-packages/kite-1.5.0-py3.10-linux-x86_64.egg/kite/quadtree.py", line 194, in theta
    theta = self.scene.theta[self._slice_rows, self._slice_cols]
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

Please help

Thank you

**Comment by raghav413** [comment]
Someone please help I am stuck there

**Comment by hvasbath** [comment]
Hi! What I can see from the limited information you provide is that you apparently only have a single scalar instead of a
 2d array in your look-angle information. The heading and incidence angle arrays need to have the exact same size as the displacement array!

**Comment by CUMT530849827** [comment]
Hi！ author, I want to use Kite to export the downsampled results in CSV format, but after several attempts, I found this error. I only found the `export_csv` method in the documentation, but no `export` method. Could you please tell me how to solve this problem? The format of the result I want to obtain is longitude, latitude, type variable, incident angle, and heading angle. Thank you very much. I'm a beginner.

![Image](https://github.com/user-attachments/assets/a84c4465-d863-4f31-9b3f-d6f75915bb06)

![Image](https://github.com/user-attachments/assets/dcad2f4d-e968-48a6-a580-f0361af2a7d8)

**Comment by hvasbath** [comment]
The documentation needs updating, sorry for that confusion. It is `export_csv`. I want to invite you to have a look at the code yourself, since you have the code here in the repository and can also check. https://github.com/pyrocko/kite/blob/master/kite/quadtree.py#L982
