### ISSUE TITLE
spool load GMTSAR result ERROR

### ISSUE THREAD

**Issue by Yaoshangheng** [pyrocko/kite#93]
Hi,
when I was loading GMTSAR unwrap_ll.grd ，It goes like that：

```
gmtsar-user@gmtsarVB:~/Desktop/myproject1_kite/data$ spool --load unwrap_ll_3.grd
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqeglfs.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archreq": 0,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqminimal.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archreq": 0,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqminimalegl.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archreq": 0,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqoffscreen.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archreq": 0,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqvnc.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archreq": 0,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwayland-egl.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwayland-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-egl"
        ]
    },
    "archreq": 0,
    "className": "QWaylandEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("wayland-egl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwayland-generic.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwayland-generic.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland"
        ]
    },
    "archreq": 0,
    "className": "QWaylandIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("wayland")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwayland-xcomposite-egl.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwayland-xcomposite-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-xcomposite-egl"
        ]
    },
    "archreq": 0,
    "className": "QWaylandXCompositeEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("wayland-xcomposite-egl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwayland-xcomposite-glx.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwayland-xcomposite-glx.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-xcomposite-glx"
        ]
    },
    "archreq": 0,
    "className": "QWaylandXCompositeGlxPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("wayland-xcomposite-glx")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwebgl.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqwebgl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "webgl"
        ]
    },
    "archreq": 0,
    "className": "QWebGLIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("webgl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so"
loaded library "Xcursor"
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platformthemes" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platformthemes/libqgtk3.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platformthemes/libqgtk3.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "gtk3"
        ]
    },
    "archreq": 0,
    "className": "QGtk3ThemePlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("gtk3")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platformthemes/libqxdgdesktopportal.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platformthemes/libqxdgdesktopportal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "xdgdesktopportal",
            "flatpak",
            "snap"
        ]
    },
    "archreq": 0,
    "className": "QXdgDesktopPortalThemePlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("xdgdesktopportal", "flatpak", "snap")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platformthemes" ...
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platformthemes/libqgtk3.so"
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforminputcontexts" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so, metadata=
{
    "IID": "org.qt-project.Qt.QPlatformInputContextFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "compose",
            "xim"
        ]
    },
    "archreq": 0,
    "className": "QComposePlatformInputContextPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("compose", "xim")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so, metadata=
{
    "IID": "org.qt-project.Qt.QPlatformInputContextFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "ibus"
        ]
    },
    "archreq": 0,
    "className": "QIbusPlatformInputContextPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("ibus")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforminputcontexts" ...
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so"
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/styles" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/styles" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "gif"
        ],
        "MimeTypes": [
            "image/gif"
        ]
    },
    "archreq": 0,
    "className": "QGifPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("gif")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "icns"
        ],
        "MimeTypes": [
            "image/x-icns"
        ]
    },
    "archreq": 0,
    "className": "QICNSPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("icns")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqico.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqico.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "ico",
            "cur"
        ],
        "MimeTypes": [
            "image/vnd.microsoft.icon",
            "image/vnd.microsoft.icon"
        ]
    },
    "archreq": 0,
    "className": "QICOPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("ico", "cur")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "jpg",
            "jpeg"
        ],
        "MimeTypes": [
            "image/jpeg",
            "image/jpeg"
        ]
    },
    "archreq": 0,
    "className": "QJpegPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("jpg", "jpeg")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz"
        ],
        "MimeTypes": [
            "image/svg+xml",
            "image/svg+xml-compressed"
        ]
    },
    "archreq": 0,
    "className": "QSvgPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("svg", "svgz")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "tga"
        ],
        "MimeTypes": [
            "image/x-tga"
        ]
    },
    "archreq": 0,
    "className": "QTgaPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("tga")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "tiff",
            "tif"
        ],
        "MimeTypes": [
            "image/tiff",
            "image/tiff"
        ]
    },
    "archreq": 0,
    "className": "QTiffPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("tiff", "tif")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "wbmp"
        ],
        "MimeTypes": [
            "image/vnd.wap.wbmp"
        ]
    },
    "archreq": 0,
    "className": "QWbmpPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("wbmp")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so, metadata=
{
    "IID": "org.qt-project.Qt.QImageIOHandlerFactoryInterface",
    "MetaData": {
        "Keys": [
            "webp"
        ],
        "MimeTypes": [
            "image/webp"
        ]
    },
    "archreq": 0,
    "className": "QWebpPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/imageformats" ...
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so"
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so"
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqico.so"
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so"
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so"
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so"
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so"
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so"
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so"
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/xcbglintegrations" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-egl-integration.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-egl-integration.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.Xcb.QXcbGlIntegrationFactoryInterface.5.5",
    "MetaData": {
        "Keys": [
            "xcb_egl"
        ]
    },
    "archreq": 0,
    "className": "QXcbEglIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("xcb_egl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.Xcb.QXcbGlIntegrationFactoryInterface.5.5",
    "MetaData": {
        "Keys": [
            "xcb_glx"
        ]
    },
    "archreq": 0,
    "className": "QXcbGlxIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("xcb_glx")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/xcbglintegrations" ...
loaded library "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so"
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/accessible" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/accessible" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/iconengines" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/iconengines/libqsvgicon.so"
Found metadata in lib /usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/iconengines/libqsvgicon.so, metadata=
{
    "IID": "org.qt-project.Qt.QIconEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz",
            "svg.gz"
        ]
    },
    "archreq": 0,
    "className": "QSvgIconPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("svg", "svgz", "svg.gz")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/iconengines" ...
WARNING:SceneIO/GMTSAR:
    Reading GMTSAR grid files.

    .. note ::

        Expects:

        * Displacement grid (NetCDF, :file:`*los_ll.grd`) in meter
          (in case use "gmt grdmath los_cm_ll.grd 0.01 MUL = los_m_ll.grd')
        * LOS binary data (see instruction, :file:`*.los.enu`)

    Calculate the corresponding unit look vectors with GMT5SAR ``SAT_look``:

    .. code-block:: sh

        gmt grd2xyz los_ll.grd | gmt grdtrack -Gdem.grd | \
        awk {'print $1, $2, $4'} | \
        SAT_look 20050731.PRM -bos > 20050731.los.enu
    
WARNING:SceneIO/GMTSAR:
    Reading GMTSAR grid files.

    .. note ::

        Expects:

        * Displacement grid (NetCDF, :file:`*los_ll.grd`) in meter
          (in case use "gmt grdmath los_cm_ll.grd 0.01 MUL = los_m_ll.grd')
        * LOS binary data (see instruction, :file:`*.los.enu`)

    Calculate the corresponding unit look vectors with GMT5SAR ``SAT_look``:

    .. code-block:: sh

        gmt grd2xyz los_ll.grd | gmt grdtrack -Gdem.grd | \
        awk {'print $1, $2, $4'} | \
        SAT_look 20050731.PRM -bos > 20050731.los.enu
    
WARNING:SceneIO/GMTSAR:Defaulting theta to pi/2 and phi to 0.
Traceback (most recent call last):
  File "/usr/local/bin/spool", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/kite/spool/__main__.py", line 111, in main
    spool(import_file=ns.load)
  File "/usr/local/lib/python3.9/dist-packages/kite/spool/spool.py", line 393, in spool
    spool_app = Spool(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/kite/spool/spool.py", line 46, in __init__
    self.importScene(import_file)
  File "/usr/local/lib/python3.9/dist-packages/kite/spool/spool.py", line 61, in importScene
    self.spool_win.model.importFile(filename)
  File "/usr/local/lib/python3.9/dist-packages/kite/spool/scene_model.py", line 171, in importFile
    self.setScene(Scene.import_data(filename))
  File "/usr/local/lib/python3.9/dist-packages/kite/scene.py", line 459, in dynclassmethod
    return func(Scene(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/kite/scene.py", line 976, in _import_data
    return scene._import_from_dict(scene, data)
  File "/usr/local/lib/python3.9/dist-packages/kite/scene.py", line 998, in _import_from_dict
    setattr(scene.frame, fk, fv)
  File "/usr/local/lib/python3.9/dist-packages/kite/scene.py", line 157, in llLon
    self.updateExtent()
  File "/usr/local/lib/python3.9/dist-packages/kite/scene.py", line 128, in updateExtent
    ) = utm.from_latlon(self.llLat, self.llLon)
  File "/usr/local/lib/python3.9/dist-packages/utm/conversion.py", line 232, in from_latlon
    raise OutOfRangeError('longitude out of range (must be between 180 deg W and 180 deg E)')
utm.error.OutOfRangeError: longitude out of range (must be between 180 deg W and 180 deg E)
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqico.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platformthemes/libqgtk3.so" 
QLibraryPrivate::unload succeeded on "/usr/local/lib/python3.9/dist-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" 
QLibraryPrivate::unload succeeded on "Xcursor" (faked)
```

Here is my .grd file，

**Comment by miili** [comment]
Please see the docs how the GMTSAR file should look. https://github.com/pyrocko/kite/blob/master/kite/scene_io.py#L795 and here https://pyrocko.org/kite/docs/current/reference/kite.scene.html#kite.scene_io.GMTSAR
